/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebapv;

import javax.swing.JOptionPane;
/**
 *
 * @author Nsandovalc
 */
public class GUI_Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form GUI_Principal
     */
    public GUI_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void BorrarPanel(){        
        jPanelPrincipal.removeAll();
        jPanelPrincipal.revalidate();
        jPanelPrincipal.repaint();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBarraPrincipal = new javax.swing.JMenuBar();
        jArchivo = new javax.swing.JMenu();
        jIniciarDB = new javax.swing.JMenuItem();
        jNuevaDB = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jVentas = new javax.swing.JMenuItem();
        jInventario = new javax.swing.JMenuItem();
        jClientes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jSalir = new javax.swing.JMenuItem();
        jSesion = new javax.swing.JMenu();
        jInicioSe = new javax.swing.JMenuItem();
        jSalirSe = new javax.swing.JMenuItem();
        jCambioSe = new javax.swing.JMenuItem();
        jAyuda = new javax.swing.JMenu();
        jAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(700, 400));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido Al Programa");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel1)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jArchivo.setText("Archivo");

        jIniciarDB.setText("Iniciar DB");
        jIniciarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIniciarDBActionPerformed(evt);
            }
        });
        jArchivo.add(jIniciarDB);

        jNuevaDB.setText("Nueva DB");
        jArchivo.add(jNuevaDB);
        jArchivo.add(jSeparator1);

        jVentas.setText("Ventas");
        jArchivo.add(jVentas);

        jInventario.setText("Inventario");
        jArchivo.add(jInventario);

        jClientes.setText("Clientes");
        jArchivo.add(jClientes);
        jArchivo.add(jSeparator2);

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        jArchivo.add(jSalir);

        jBarraPrincipal.add(jArchivo);

        jSesion.setText("Secion");

        jInicioSe.setText("Iniciar sesion");
        jInicioSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInicioSeActionPerformed(evt);
            }
        });
        jSesion.add(jInicioSe);

        jSalirSe.setText("Salir de sesion");
        jSalirSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirSeActionPerformed(evt);
            }
        });
        jSesion.add(jSalirSe);

        jCambioSe.setText("Cambiar de sesion");
        jSesion.add(jCambioSe);

        jBarraPrincipal.add(jSesion);

        jAyuda.setText("Ayuda");

        jAcercaDe.setText("Acerca de");
        jAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAcercaDeActionPerformed(evt);
            }
        });
        jAyuda.add(jAcercaDe);

        jBarraPrincipal.add(jAyuda);

        setJMenuBar(jBarraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(rootPane, "¿Desea salir?",
                "Salir del programa", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    private void jIniciarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIniciarDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIniciarDBActionPerformed

    private void jSalirSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirSeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSalirSeActionPerformed

    private void jInicioSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInicioSeActionPerformed
        // TODO add your handling code here:
        PanelLogin login = new PanelLogin();   
        login.setSize(300,160);        
        //login.setLocation(350,100);
        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(login);
        jPanelPrincipal.revalidate();
        jPanelPrincipal.repaint();
    }//GEN-LAST:event_jInicioSeActionPerformed

    private void jAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAcercaDeActionPerformed
        // TODO add your handling code here:
        BorrarPanel();
    }//GEN-LAST:event_jAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAcercaDe;
    private javax.swing.JMenu jArchivo;
    private javax.swing.JMenu jAyuda;
    private javax.swing.JMenuBar jBarraPrincipal;
    private javax.swing.JMenuItem jCambioSe;
    private javax.swing.JMenuItem jClientes;
    private javax.swing.JMenuItem jIniciarDB;
    private javax.swing.JMenuItem jInicioSe;
    private javax.swing.JMenuItem jInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jNuevaDB;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JMenuItem jSalir;
    private javax.swing.JMenuItem jSalirSe;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu jSesion;
    private javax.swing.JMenuItem jVentas;
    // End of variables declaration//GEN-END:variables
}
